langugage: python
python:
    - "3.8"

services:
    - docker

before_script: pip install docker-compose flake8

script:
    - docker-compose run airflow sh -c "python -m pytest -v --show-capture=no" && python -m flake8 -v
