langugage: python
python:
    - "3.8"

services:
    - docker

before_script: 
    - pip install docker-compose flake8 python-coveralls coveralls

script:
    - bash ./run_tests.sh

after_success:
    - coveralls